const IDENTIFIER = '[root]';// @@root

export const GET_PETS_REQUEST = `${IDENTIFIER}GET_PETS_REQUEST`;
export const GET_PETS_SUCCESS = `${IDENTIFIER}GET_PETS_SUCCESS`;
export const GET_PETS_FAILED = `${IDENTIFIER}GET_PETS_FAILED`;

export const CLEAR_PETS = `${IDENTIFIER}CLEAR_PETS`;

export const GET_SERVICES_REQUEST = `${IDENTIFIER}GET_SERVICES_REQUEST`;
export const GET_SERVICES_SUCCESS = `${IDENTIFIER}GET_SERVICES_SUCCESS`;
export const GET_SERVICES_FAILED = `${IDENTIFIER}GET_SERVICES_FAILED`;

export const CLEAR_SERVICES = `${IDENTIFIER}CLEAR_SERVICES`;
